function footerText() {
    const footers = [
        'give me a soft word,',
        "we're diferent but the same,",
        'time to think,',
        'what is beauty if not the tearful laughter of your beloved,',
        'the wind knows my secrets,',
        'it was the best of times it was the worst of times, and no one knows about nuance,',
        "sharks in the bathtub and we're all swimming,",
        'ripping away anything that distances me from reality, from this moment,',
        'with forlorn musings,',
        'worth a visit,',
        'no questions asked,',
        'from memory,',
        'part of the process,',
        'woo!,',
        'emancipation awaits,',
        'i would not be here without you,',
        'totally execellent,',
        'to time, for all this time,',
        'bery vest,',
        'heroically,',
        'leaving you with all my problems, i remain,',
        'so until then i remain inconsistently,',
        'bottom text,',
        'waving from afar,',
        "it's still going on,",
        'husking in the wind,',
        'auld lang syne motherfuckers,',
        'stay sweet,',
        'typing off,',
        // 29 up to here
        'may your soul be overgrown with moss. may your veins fill with rainwater and your lungs swell with flowers,',
        'heck if i know,',
        "i feel like something's missing,",
        'are we certain how we feel about all this?,',
        'i forgot to wash my face,',
        'permanently overwhelmed,',
        'is this it?,',
        'to start a garden,',
        'never date a poet,',
        'hoping we run into each other,',
        'is it enough,',
        'falling back to earth,',
        'seen,',
        'on being left behind,',
        "i'm about to lose my mind,",
        'sorry for the angst,',
        'no rush,',
        'i hope your flowers bloom,',
        'keep going,',
        'unbuttoned,',
        'listening to myself,',
        'see ya after the end of the world,',
        // 51 up to here
    ];

    return footers[Math.floor((Math.random() * 50.99))];
}

document.getElementById('footerText').innerHTML = footerText();